//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busmanagemnetsystem.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistory
    {
        public int BookingHistoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TicketID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string Status { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
