//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busmanagemnetsystem.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string From_Station { get; set; }
        public string To_Station { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BusID { get; set; }
        public string SeatNumber { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual User User { get; set; }
    }
}
