//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busmanagemnetsystem.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.BookingHistories = new HashSet<BookingHistory>();
        }
    
        public int TicketID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PassengerName { get; set; }
        public string SeatNumber { get; set; }
        public int NumberOfSeats { get; set; }
        public Nullable<int> BusID { get; set; }
        public string BusName { get; set; }
        public System.DateTime BookingDate { get; set; }
        public decimal Fare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingHistory> BookingHistories { get; set; }
        public virtual Bus Bus { get; set; }
        public virtual User User { get; set; }
    }
}
