//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class Employee
    {
        [Required(ErrorMessage = "Employee Id is required")]
        public int Emp_ID { get; set; }

        [Required(ErrorMessage = "Please enter First Name ")]
        public string Emp_First_Name { get; set; }

        [Required(ErrorMessage = "Please enter Last Name")]
        public string Emp_Last_Name { get; set; }
        public Nullable<System.DateTime> Emp_Date_of_Birth { get; set; }
        public Nullable<System.DateTime> Emp_Date_of_Joining { get; set; }
        public Nullable<int> Emp_Dept_ID { get; set; }
        public string Emp_Grade { get; set; }
        public string Emp_Designation { get; set; }
        public Nullable<decimal> Emp_Salary { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_Marital_Status { get; set; }
        public string Emp_Home_Address { get; set; }

        [RegularExpression(@"^\d{10}$", ErrorMessage = "Contact number must be 10 digits")]
        public string Emp_Contact_Num { get; set; }
        public bool IsDeleted { get; set; }
        public string IsActive { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Grade_master Grade_master { get; set; }
    }
}
